spring:
  datasource:
    password: ymy123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/exercise?serverTimezone=UTC
  session:
    timeout: 86400
